name: 02 basics workflow
on:
  push:
    branches: [main]
  issues:
defaults:
  run:
    working-directory: 'Code/02 Basics/04 Practice Project (Start)'
# jobs:
#   deploy:
#     name: Deploy code
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3
#       - name: Install Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'
#       - name: Install code
#         run: npm ci
#       - name: Run lint
#         run: npm run lint
#       - name: Run test
#         run: npm run test
#       - name: Build step``
#         run: npm run build
#       - name: deploy
#         run: echo "DEPLOYING ... ✅"
#       - name: Echo github context
#         run: echo "${{ toJSON(github) }}"
jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install code
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Build step
        run: npm run build
      - name: deploy
        run: echo "DEPLOYING ... ✅"
      - name: Echo github context
        run: echo "${{ toJSON(github) }}"
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install code
        run: npm ci
      - name: Test code
        run: npm run test
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install code
        run: npm ci
      - name: Build code
        run: npm run build
  deploy:
    name: Deploy code
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install code
        run: npm ci
      - name: Deploy code
        run: echo "DEPLOYING BOOM"
